version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: winwin_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-api:
    build: ./auth-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/winwin_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
      DATA_API_URL: http://data-api:8081/api/transform
    depends_on:
      - postgres
    networks:
      - app-network

  data-api:
    build: ./data-api
    ports:
      - "8081:8081"
    environment:
      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: